import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import {
  assertOrgCapability,
  getOrgPermissionContext,
  mapPermissionErrorToStatus,
} from "@/lib/org/permissions.server";
import { getUnifiedAuth } from "@/lib/unified-auth";
import { logOrgAudit } from "@/lib/orgAudit";

type CreateInviteBody = {
  email: string;
  roleName?: string;
};

export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ orgId: string }> }
) {
  const resolvedParams = await params;
  const orgId = resolvedParams.orgId;

  if (!orgId) {
    return NextResponse.json(
      {
        ok: false,
        error: { code: "MISSING_ORG_ID", message: "Organization id is required." },
      },
      { status: 400 }
    );
  }

  try {
    const context = await getOrgPermissionContext(req);

    try {
      assertOrgCapability(context, "org:member:invite");
    } catch (permError) {
      const status = mapPermissionErrorToStatus(permError);
      return NextResponse.json(
        {
          ok: false,
          error: {
            code: status === 401 ? "UNAUTHORIZED" : "FORBIDDEN",
            message: "You are not allowed to invite members to this org.",
          },
        },
        { status }
      );
    }

    // Verify orgId matches context
    if (context!.orgId !== orgId) {
      return NextResponse.json(
        {
          ok: false,
          error: {
            code: "ORG_MISMATCH",
            message: "Organization ID mismatch.",
          },
        },
        { status: 400 }
      );
    }

    // Get current user for invitedById
    const auth = await getUnifiedAuth(req);
    const invitedById = auth.user.userId;

    const body = (await req.json()) as CreateInviteBody;
    const email = body.email?.trim();

    if (!email) {
      return NextResponse.json(
        {
          ok: false,
          error: { code: "INVALID_EMAIL", message: "Invite email is required." },
        },
        { status: 400 }
      );
    }

    // Check if user is already a member
    const existingUser = await prisma.user.findUnique({
      where: { email },
    });

    if (existingUser) {
      const existingMember = await prisma.workspaceMember.findFirst({
        where: {
          workspaceId: orgId,
          userId: existingUser.id,
        },
      });

      if (existingMember) {
        return NextResponse.json(
          {
            ok: false,
            error: {
              code: "ALREADY_MEMBER",
              message: "User is already a member of this organization.",
            },
          },
          { status: 409 }
        );
      }
    }

    // Check if there's already a pending invite
    const existingInvite = await prisma.orgInvitation.findFirst({
      where: {
        workspaceId: orgId,
        email,
        status: "PENDING",
      },
    });

    if (existingInvite) {
      return NextResponse.json(
        {
          ok: false,
          error: {
            code: "INVITE_EXISTS",
            message: "A pending invitation already exists for this email.",
          },
        },
        { status: 409 }
      );
    }

    // Create the invite
    const invite = await prisma.orgInvitation.create({
      data: {
        workspaceId: orgId,
        email,
        status: "PENDING",
        invitedById,
        token: undefined, // Will be auto-generated by Prisma default
      },
    });

    // Audit log (best-effort)
    await logOrgAudit(
      {
        orgId,
        action: "INVITE_CREATED",
        targetType: "INVITE",
        targetId: invite.id,
        meta: {
          email,
        },
      },
      req
    );

    return NextResponse.json({
      ok: true,
      data: invite,
    });
  } catch (error) {
    console.error("[org-invites-post]", error);

    return NextResponse.json(
      {
        ok: false,
        error: {
          code: "INTERNAL_ERROR",
          message: "Failed to create invite.",
        },
      },
      { status: 500 }
    );
  }
}

// GET /api/org/[orgId]/invites - List invites (Admin+ only)
export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ orgId: string }> }
) {
  const resolvedParams = await params;
  const orgId = resolvedParams.orgId;

  if (!orgId) {
    return NextResponse.json(
      {
        ok: false,
        error: { code: "MISSING_ORG_ID", message: "Organization id is required." },
      },
      { status: 400 }
    );
  }

  try {
    const context = await getOrgPermissionContext(req);

    try {
      assertOrgCapability(context, "org:member:invite");
    } catch (permError) {
      const status = mapPermissionErrorToStatus(permError);
      return NextResponse.json(
        {
          ok: false,
          error: {
            code: status === 401 ? "UNAUTHORIZED" : "FORBIDDEN",
            message: "You are not allowed to view invites for this org.",
          },
        },
        { status }
      );
    }

    // Verify orgId matches context
    if (context!.orgId !== orgId) {
      return NextResponse.json(
        {
          ok: false,
          error: {
            code: "ORG_MISMATCH",
            message: "Organization ID mismatch.",
          },
        },
        { status: 400 }
      );
    }

    const invites = await prisma.orgInvitation.findMany({
      where: { workspaceId: orgId },
      orderBy: { createdAt: "desc" },
      include: {
        invitedBy: {
          select: {
            id: true,
            name: true,
            email: true,
          },
        },
      },
    });

    return NextResponse.json({ ok: true, data: invites }, { status: 200 });
  } catch (error) {
    console.error("[org-invites-get]", error);
    return NextResponse.json(
      {
        ok: false,
        error: {
          code: "INTERNAL_ERROR",
          message: "Failed to load invites.",
        },
      },
      { status: 500 }
    );
  }
}

