CREATE INDEX IF NOT EXISTS idx_workspace_members_user_workspace ON workspace_members("userId", "workspaceId");
CREATE INDEX IF NOT EXISTS idx_wiki_pages_workspace_published ON wiki_pages("workspaceId", "isPublished") WHERE "isPublished" = true;
CREATE INDEX IF NOT EXISTS idx_wiki_pages_workspace_type ON wiki_pages("workspaceId", "workspace_type");
CREATE INDEX IF NOT EXISTS idx_wiki_pages_updated_at ON wiki_pages("updatedAt" DESC);
CREATE INDEX IF NOT EXISTS idx_projects_workspace_status ON projects("workspaceId", "status");
CREATE INDEX IF NOT EXISTS idx_projects_updated_at ON projects("updatedAt" DESC);
CREATE INDEX IF NOT EXISTS idx_chat_sessions_workspace_user_draft ON chat_sessions("workspaceId", "userId", "phase") WHERE "draftTitle" IS NOT NULL AND "draftBody" IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_chat_sessions_updated_at ON chat_sessions("updatedAt" DESC);
CREATE INDEX IF NOT EXISTS idx_wiki_workspaces_workspace_type ON wiki_workspaces(workspace_id, type);
CREATE INDEX IF NOT EXISTS idx_tasks_workspace_status ON tasks("workspaceId", "status");
CREATE INDEX IF NOT EXISTS idx_tasks_project_status ON tasks("projectId", "status") WHERE "projectId" IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_wiki_favorites_user_workspace ON wiki_favorites(user_id, page_id);
CREATE INDEX IF NOT EXISTS idx_wiki_comments_page_created ON wiki_comments("pageId", "createdAt" DESC);
ANALYZE workspace_members;
ANALYZE wiki_pages;
ANALYZE projects;
ANALYZE chat_sessions;
ANALYZE wiki_workspaces;
ANALYZE tasks;
