/**
 * Acme Analytics — 20-person org roster
 *
 * Keys are stable identifiers used to wire up manager references,
 * project membership, and wiki authorship. Actual DB IDs are CUIDs
 * assigned at creation time.
 */

export interface AcmePerson {
  key: string
  name: string
  email: string
  title: string
  departmentKey: string
  teamKey: string
  managerKey: string | null
  startDate: Date
  bio: string
  skills: string[]
  level: number
  workspaceRole: 'OWNER' | 'ADMIN' | 'MEMBER'
}

const d = (y: number, m: number, day: number) => new Date(y, m - 1, day)

export const ACME_PEOPLE: AcmePerson[] = [
  // ── Executive ──────────────────────────────────────────────
  {
    key: 'sarah-chen',
    name: 'Sarah Chen',
    email: 'sarah.chen@acme-analytics.com',
    title: 'Chief Executive Officer',
    departmentKey: 'executive',
    teamKey: 'leadership',
    managerKey: null,
    startDate: d(2024, 1, 15),
    bio: 'Former VP of Product at Datadog with 15 years in enterprise SaaS. Founded Acme Analytics to democratize data visualization for mid-market companies. Stanford MBA.',
    skills: ['Strategy', 'Fundraising', 'Product Vision', 'Board Management'],
    level: 6,
    workspaceRole: 'OWNER',
  },

  // ── CTO ────────────────────────────────────────────────────
  {
    key: 'marcus-rodriguez',
    name: 'Marcus Rodriguez',
    email: 'marcus.rodriguez@acme-analytics.com',
    title: 'Chief Technology Officer',
    departmentKey: 'engineering',
    teamKey: 'leadership',
    managerKey: 'sarah-chen',
    startDate: d(2024, 2, 1),
    bio: 'Built the real-time analytics pipeline at Segment before joining as co-founder. 12 years of experience in distributed systems and data infrastructure. Writes Rust on weekends.',
    skills: ['System Architecture', 'Distributed Systems', 'Rust', 'Go', 'AWS', 'Team Building'],
    level: 6,
    workspaceRole: 'ADMIN',
  },

  // ── CPO ────────────────────────────────────────────────────
  {
    key: 'emma-thompson',
    name: 'Emma Thompson',
    email: 'emma.thompson@acme-analytics.com',
    title: 'Chief Product Officer',
    departmentKey: 'product-design',
    teamKey: 'leadership',
    managerKey: 'sarah-chen',
    startDate: d(2024, 3, 1),
    bio: 'Led product for Looker\'s enterprise dashboard suite before acquisition. Obsessed with reducing time-to-insight for non-technical users. Holds 3 patents in data visualization.',
    skills: ['Product Strategy', 'User Research', 'Data Visualization', 'Roadmapping', 'Figma'],
    level: 6,
    workspaceRole: 'ADMIN',
  },

  // ── Head of GTM ────────────────────────────────────────────
  {
    key: 'david-wilson',
    name: 'David Wilson',
    email: 'david.wilson@acme-analytics.com',
    title: 'Head of Go-to-Market',
    departmentKey: 'gtm',
    teamKey: 'leadership',
    managerKey: 'sarah-chen',
    startDate: d(2024, 4, 15),
    bio: 'Scaled Amplitude\'s sales team from 5 to 40 reps in 18 months. Expert in product-led growth with enterprise overlay motions. Believes the best product wins but distribution determines when.',
    skills: ['Sales Strategy', 'PLG', 'Enterprise Sales', 'Team Scaling', 'Revenue Ops'],
    level: 5,
    workspaceRole: 'ADMIN',
  },

  // ── Head of Ops ────────────────────────────────────────────
  {
    key: 'rachel-green',
    name: 'Rachel Green',
    email: 'rachel.green@acme-analytics.com',
    title: 'Head of Operations',
    departmentKey: 'operations',
    teamKey: 'leadership',
    managerKey: 'sarah-chen',
    startDate: d(2024, 5, 1),
    bio: 'Former COO of a fintech startup that grew from seed to Series B. Specializes in building operational infrastructure for hypergrowth companies. CPA with an MBA from Wharton.',
    skills: ['Operations', 'Finance', 'HR', 'Legal', 'Process Optimization'],
    level: 5,
    workspaceRole: 'ADMIN',
  },

  // ── Engineering: Backend ───────────────────────────────────
  {
    key: 'james-kim',
    name: 'James Kim',
    email: 'james.kim@acme-analytics.com',
    title: 'Backend Team Lead',
    departmentKey: 'engineering',
    teamKey: 'backend',
    managerKey: 'marcus-rodriguez',
    startDate: d(2024, 3, 15),
    bio: 'Spent 6 years at Stripe building payment processing APIs handling millions of transactions per day. Passionate about API design, observability, and mentoring engineers through complex problems.',
    skills: ['Node.js', 'TypeScript', 'PostgreSQL', 'Redis', 'API Design', 'Observability'],
    level: 4,
    workspaceRole: 'MEMBER',
  },
  {
    key: 'priya-sharma',
    name: 'Priya Sharma',
    email: 'priya.sharma@acme-analytics.com',
    title: 'Senior Backend Engineer',
    departmentKey: 'engineering',
    teamKey: 'backend',
    managerKey: 'james-kim',
    startDate: d(2024, 6, 1),
    bio: 'Data pipeline specialist who previously built ETL infrastructure at Fivetran. Expert in streaming architectures and query optimization. Contributes to Apache Arrow in her spare time.',
    skills: ['Python', 'TypeScript', 'Kafka', 'PostgreSQL', 'Data Pipelines', 'Apache Arrow'],
    level: 3,
    workspaceRole: 'MEMBER',
  },
  {
    key: 'noah-williams',
    name: 'Noah Williams',
    email: 'noah.williams@acme-analytics.com',
    title: 'Backend Engineer',
    departmentKey: 'engineering',
    teamKey: 'backend',
    managerKey: 'james-kim',
    startDate: d(2025, 1, 10),
    bio: 'Joined from a YC-batch startup where he built the core GraphQL API layer. Quick learner with strong CS fundamentals and a knack for writing clean, well-tested code.',
    skills: ['TypeScript', 'GraphQL', 'Node.js', 'PostgreSQL', 'Docker'],
    level: 2,
    workspaceRole: 'MEMBER',
  },
  {
    key: 'fatima-al-rashid',
    name: 'Fatima Al-Rashid',
    email: 'fatima.alrashid@acme-analytics.com',
    title: 'Backend Engineer',
    departmentKey: 'engineering',
    teamKey: 'backend',
    managerKey: 'james-kim',
    startDate: d(2025, 9, 15),
    bio: 'Recent computer science graduate from MIT with two internships at Google. Focused on database internals and distributed consensus algorithms. Already shipping production features in her first month.',
    skills: ['Go', 'TypeScript', 'PostgreSQL', 'Algorithms', 'Distributed Systems'],
    level: 1,
    workspaceRole: 'MEMBER',
  },

  // ── Engineering: Frontend ──────────────────────────────────
  {
    key: 'lisa-zhang',
    name: 'Lisa Zhang',
    email: 'lisa.zhang@acme-analytics.com',
    title: 'Frontend Team Lead',
    departmentKey: 'engineering',
    teamKey: 'frontend',
    managerKey: 'marcus-rodriguez',
    startDate: d(2024, 4, 1),
    bio: 'Built Figma\'s real-time collaboration layer and led the charting component library at Observable. Deep expertise in canvas rendering, WebGL, and making complex data feel intuitive.',
    skills: ['React', 'TypeScript', 'WebGL', 'Canvas', 'D3.js', 'Performance Optimization'],
    level: 4,
    workspaceRole: 'MEMBER',
  },
  {
    key: 'tyler-okonkwo',
    name: 'Tyler Okonkwo',
    email: 'tyler.okonkwo@acme-analytics.com',
    title: 'Senior Frontend Engineer',
    departmentKey: 'engineering',
    teamKey: 'frontend',
    managerKey: 'lisa-zhang',
    startDate: d(2024, 8, 1),
    bio: 'Accessibility-first engineer who previously led the design system team at Shopify. Strong advocate for inclusive design and performance budgets. Speaks at React conferences.',
    skills: ['React', 'TypeScript', 'Accessibility', 'Design Systems', 'CSS', 'Testing'],
    level: 3,
    workspaceRole: 'MEMBER',
  },
  {
    key: 'maria-santos',
    name: 'Maria Santos',
    email: 'maria.santos@acme-analytics.com',
    title: 'Frontend Engineer',
    departmentKey: 'engineering',
    teamKey: 'frontend',
    managerKey: 'lisa-zhang',
    startDate: d(2025, 3, 1),
    bio: 'Full-stack bootcamp graduate turned frontend specialist. Built interactive data dashboards at a climate tech startup. Brings a unique perspective from her background in environmental science.',
    skills: ['React', 'TypeScript', 'Next.js', 'Tailwind CSS', 'Chart.js'],
    level: 2,
    workspaceRole: 'MEMBER',
  },

  // ── Engineering: DevOps ────────────────────────────────────
  {
    key: 'alex-patel',
    name: 'Alex Patel',
    email: 'alex.patel@acme-analytics.com',
    title: 'Senior DevOps Engineer',
    departmentKey: 'engineering',
    teamKey: 'devops',
    managerKey: 'marcus-rodriguez',
    startDate: d(2024, 5, 15),
    bio: 'Kubernetes expert who ran infrastructure for a 500-node cluster at Cloudflare. Automates everything. Maintains the company\'s Terraform modules and built the CI/CD pipeline from scratch.',
    skills: ['Kubernetes', 'Terraform', 'AWS', 'GitHub Actions', 'Docker', 'Monitoring'],
    level: 3,
    workspaceRole: 'MEMBER',
  },

  // ── Product & Design ───────────────────────────────────────
  {
    key: 'raj-krishnamurthy',
    name: 'Raj Krishnamurthy',
    email: 'raj.krishnamurthy@acme-analytics.com',
    title: 'Senior Product Manager',
    departmentKey: 'product-design',
    teamKey: 'product',
    managerKey: 'emma-thompson',
    startDate: d(2024, 6, 15),
    bio: 'Ex-Mixpanel PM who shipped their enterprise analytics suite. Thinks in user journeys and measures everything. Bridges the gap between what customers ask for and what they actually need.',
    skills: ['Product Management', 'Analytics', 'User Research', 'SQL', 'Roadmapping'],
    level: 3,
    workspaceRole: 'MEMBER',
  },
  {
    key: 'olivia-park',
    name: 'Olivia Park',
    email: 'olivia.park@acme-analytics.com',
    title: 'Product Manager',
    departmentKey: 'product-design',
    teamKey: 'product',
    managerKey: 'emma-thompson',
    startDate: d(2025, 2, 1),
    bio: 'Transitioned from data science to product management at Tableau. Brings quantitative rigor to feature prioritization and loves running experiments to validate hypotheses before building.',
    skills: ['Product Management', 'Data Science', 'A/B Testing', 'Python', 'Figma'],
    level: 2,
    workspaceRole: 'MEMBER',
  },
  {
    key: 'daniel-nakamura',
    name: 'Daniel Nakamura',
    email: 'daniel.nakamura@acme-analytics.com',
    title: 'Senior UX Designer',
    departmentKey: 'product-design',
    teamKey: 'design',
    managerKey: 'emma-thompson',
    startDate: d(2024, 7, 1),
    bio: 'Designed the onboarding flow at Notion that increased activation by 40%. Specializes in complex information architecture and making dense data feel approachable. Runs weekly design critiques.',
    skills: ['UX Design', 'Figma', 'Prototyping', 'User Research', 'Information Architecture'],
    level: 3,
    workspaceRole: 'MEMBER',
  },
  {
    key: 'sophie-dubois',
    name: 'Sophie Dubois',
    email: 'sophie.dubois@acme-analytics.com',
    title: 'UI Designer',
    departmentKey: 'product-design',
    teamKey: 'design',
    managerKey: 'emma-thompson',
    startDate: d(2025, 5, 1),
    bio: 'Visual design specialist with a fine arts background. Previously at a branding agency working with SaaS clients. Owns the Acme design system and ensures every pixel tells a story.',
    skills: ['UI Design', 'Figma', 'Illustration', 'Design Systems', 'Brand Design'],
    level: 2,
    workspaceRole: 'MEMBER',
  },

  // ── Go-to-Market: Sales ────────────────────────────────────
  {
    key: 'chris-hernandez',
    name: 'Chris Hernandez',
    email: 'chris.hernandez@acme-analytics.com',
    title: 'Senior Account Executive',
    departmentKey: 'gtm',
    teamKey: 'sales',
    managerKey: 'david-wilson',
    startDate: d(2024, 7, 15),
    bio: 'Closed the first enterprise deal at Acme. Previously at Snowflake where he consistently exceeded quota selling to Fortune 500 data teams. Relationship-driven seller who understands technical buyers.',
    skills: ['Enterprise Sales', 'Solution Selling', 'Salesforce', 'Negotiation', 'Account Planning'],
    level: 3,
    workspaceRole: 'MEMBER',
  },
  {
    key: 'aisha-johnson',
    name: 'Aisha Johnson',
    email: 'aisha.johnson@acme-analytics.com',
    title: 'Account Executive',
    departmentKey: 'gtm',
    teamKey: 'sales',
    managerKey: 'david-wilson',
    startDate: d(2025, 1, 15),
    bio: 'Mid-market sales specialist who cut her teeth at HubSpot. Excels at running efficient sales cycles and building repeatable playbooks. Hit 120% of quota in her first quarter at Acme.',
    skills: ['Sales', 'Salesforce', 'Demo Skills', 'Pipeline Management', 'Cold Outreach'],
    level: 2,
    workspaceRole: 'MEMBER',
  },
  {
    key: 'brandon-lee',
    name: 'Brandon Lee',
    email: 'brandon.lee@acme-analytics.com',
    title: 'Account Executive',
    departmentKey: 'gtm',
    teamKey: 'sales',
    managerKey: 'david-wilson',
    startDate: d(2025, 6, 1),
    bio: 'Former SDR promoted to AE after crushing his outbound targets for three consecutive quarters. Natural storyteller who connects product capabilities to business outcomes in every conversation.',
    skills: ['Sales', 'Outbound', 'Storytelling', 'Salesforce', 'LinkedIn Sales Nav'],
    level: 2,
    workspaceRole: 'MEMBER',
  },

  // ── Go-to-Market: Marketing ────────────────────────────────
  {
    key: 'megan-obrien',
    name: "Megan O'Brien",
    email: 'megan.obrien@acme-analytics.com',
    title: 'Marketing Manager',
    departmentKey: 'gtm',
    teamKey: 'marketing',
    managerKey: 'david-wilson',
    startDate: d(2024, 9, 1),
    bio: 'Demand generation expert who built the content engine at Dbt Labs. Runs Acme\'s webinar program, paid campaigns, and event strategy. Data-driven marketer who A/B tests everything.',
    skills: ['Demand Gen', 'Content Marketing', 'Google Ads', 'HubSpot', 'Analytics'],
    level: 3,
    workspaceRole: 'MEMBER',
  },
  {
    key: 'yuki-tanaka',
    name: 'Yuki Tanaka',
    email: 'yuki.tanaka@acme-analytics.com',
    title: 'Content Marketing Manager',
    departmentKey: 'gtm',
    teamKey: 'marketing',
    managerKey: 'david-wilson',
    startDate: d(2025, 4, 1),
    bio: 'Technical writer turned content marketer. Creates the blog posts, case studies, and thought leadership that drive 60% of inbound leads. Previously wrote developer documentation at Vercel.',
    skills: ['Content Strategy', 'Technical Writing', 'SEO', 'Blog', 'Case Studies'],
    level: 2,
    workspaceRole: 'MEMBER',
  },

  // ── Operations ─────────────────────────────────────────────
  {
    key: 'kevin-nguyen',
    name: 'Kevin Nguyen',
    email: 'kevin.nguyen@acme-analytics.com',
    title: 'Finance Controller',
    departmentKey: 'operations',
    teamKey: 'ops-team',
    managerKey: 'rachel-green',
    startDate: d(2024, 8, 15),
    bio: 'CPA with 8 years at Deloitte before moving to startups. Manages Acme\'s financial planning, runway modeling, and investor reporting. Built the company\'s first financial model from scratch.',
    skills: ['Financial Planning', 'Accounting', 'Excel', 'QuickBooks', 'Investor Relations'],
    level: 3,
    workspaceRole: 'MEMBER',
  },
  {
    key: 'hannah-foster',
    name: 'Hannah Foster',
    email: 'hannah.foster@acme-analytics.com',
    title: 'People Operations Manager',
    departmentKey: 'operations',
    teamKey: 'ops-team',
    managerKey: 'rachel-green',
    startDate: d(2025, 1, 5),
    bio: 'HR generalist who scaled people ops at two YC startups from 10 to 80 employees. Owns recruiting, onboarding, benefits, and culture initiatives. Certified SHRM-CP.',
    skills: ['Recruiting', 'Onboarding', 'Benefits Admin', 'HRIS', 'Culture Building'],
    level: 2,
    workspaceRole: 'MEMBER',
  },
  {
    key: 'jordan-mitchell',
    name: 'Jordan Mitchell',
    email: 'jordan.mitchell@acme-analytics.com',
    title: 'Customer Success Manager',
    departmentKey: 'operations',
    teamKey: 'ops-team',
    managerKey: 'rachel-green',
    startDate: d(2025, 7, 1),
    bio: 'Manages Acme\'s top 15 accounts and runs the quarterly business review program. Previously at Gainsight where he reduced churn by 30% for his book of business. Voice of the customer internally.',
    skills: ['Customer Success', 'Account Management', 'Gainsight', 'Churn Prevention', 'QBRs'],
    level: 2,
    workspaceRole: 'MEMBER',
  },
]
