/**
 * Acme Analytics — Wiki Pages
 *
 * 50 pages across 6 categories with realistic content.
 * Pages with parentKey form a hierarchy (sections → child pages).
 * Person keys reference acme-people.ts for authorship.
 */

export interface AcmeWikiPage {
  key: string
  title: string
  slug: string
  content: string
  category: string
  tags: string[]
  type: 'COMPANY_WIKI' | 'TEAM_DOC' | 'PROJECT_DOC' | 'PERSONAL_NOTE'
  createdByKey: string
  parentKey: string | null
  isSection: boolean
  daysAgo: number
  updatedDaysAgo: number
}

export const ACME_WIKI_PAGES: AcmeWikiPage[] = [
  // ═══════════════════════════════════════════════════════════
  // COMPANY HANDBOOK (8 pages)
  // ═══════════════════════════════════════════════════════════
  {
    key: 'handbook-section',
    title: 'Company Handbook',
    slug: 'company-handbook',
    content: '<h1>Acme Analytics Company Handbook</h1><p>Welcome to the Acme Analytics company handbook. This is your single source of truth for company policies, benefits, and how we work together. If something is missing or outdated, please flag it in #handbook-updates on Slack.</p>',
    category: 'handbook',
    tags: ['handbook', 'company', 'policies'],
    type: 'COMPANY_WIKI',
    createdByKey: 'sarah-chen',
    parentKey: null,
    isSection: true,
    daysAgo: 180,
    updatedDaysAgo: 30,
  },
  {
    key: 'mission-values',
    title: 'Mission, Vision & Values',
    slug: 'mission-vision-values',
    content: '<h2>Our Mission</h2><p>Acme Analytics exists to make data visualization accessible to every team, not just data engineers. We believe that when people can see their data clearly, they make better decisions faster.</p><h2>Our Vision</h2><p>A world where every business decision is informed by data, and the tools to explore that data are as intuitive as a spreadsheet but as powerful as a data warehouse.</p><h2>Our Values</h2><p><strong>Clarity over complexity.</strong> We choose the simplest solution that solves the problem. If a feature needs a manual to explain, we haven\'t finished designing it.</p><p><strong>Ship and iterate.</strong> We\'d rather ship something imperfect and learn from real usage than spend months perfecting a feature in isolation. Every release is a hypothesis to validate.</p><p><strong>Trust by default.</strong> We assume good intent, share context generously, and give people the autonomy to do their best work. Transparency is our operating system.</p><p><strong>Customer obsession.</strong> We talk to customers every week. Their problems are our roadmap. Every feature we build should trace back to a real user need.</p>',
    category: 'handbook',
    tags: ['handbook', 'mission', 'values', 'culture'],
    type: 'COMPANY_WIKI',
    createdByKey: 'sarah-chen',
    parentKey: 'handbook-section',
    isSection: false,
    daysAgo: 180,
    updatedDaysAgo: 60,
  },
  {
    key: 'benefits-perks',
    title: 'Benefits & Perks',
    slug: 'benefits-and-perks',
    content: '<h2>Health Insurance</h2><p>We cover 100% of employee premiums and 75% of dependent premiums through Anthem Blue Cross. Dental and vision are included. Coverage starts on your first day.</p><h2>Time Off</h2><p>Unlimited PTO with a minimum of 15 days per year. We track usage to make sure people actually take time off. Managers are expected to model healthy time-off behavior. We also observe all US federal holidays plus the week between Christmas and New Year\'s.</p><h2>Equipment</h2><p>Every employee receives a $3,000 equipment stipend for their home office setup. This covers a laptop (MacBook Pro is the default), monitor, keyboard, and chair. Replacements are available every 3 years or as needed.</p><h2>Professional Development</h2><p>$1,500 annual learning budget for conferences, courses, books, and certifications. We encourage engineers to attend at least one conference per year and share what they learned in a lunch-and-learn.</p>',
    category: 'handbook',
    tags: ['handbook', 'benefits', 'perks', 'hr'],
    type: 'COMPANY_WIKI',
    createdByKey: 'hannah-foster',
    parentKey: 'handbook-section',
    isSection: false,
    daysAgo: 150,
    updatedDaysAgo: 45,
  },
  {
    key: 'pto-policy',
    title: 'PTO & Leave Policy',
    slug: 'pto-leave-policy',
    content: '<h2>Requesting Time Off</h2><p>Submit PTO requests in the HR portal at least 2 weeks in advance for planned vacations. For sick days or emergencies, notify your manager on the day. No approval is needed for 1-2 day absences — just update your Slack status and calendar.</p><h2>Parental Leave</h2><p>16 weeks of fully paid parental leave for all new parents (birth, adoption, or foster placement). An additional 4 weeks of part-time transition is available when returning to work. This applies regardless of gender or family structure.</p><h2>Sabbatical</h2><p>After 3 years of continuous employment, you\'re eligible for a 4-week paid sabbatical. Use it however you want — travel, learn something new, or just recharge. Sarah took hers to hike the Camino de Santiago.</p>',
    category: 'handbook',
    tags: ['handbook', 'pto', 'leave', 'parental'],
    type: 'COMPANY_WIKI',
    createdByKey: 'hannah-foster',
    parentKey: 'handbook-section',
    isSection: false,
    daysAgo: 150,
    updatedDaysAgo: 90,
  },
  {
    key: 'code-of-conduct',
    title: 'Code of Conduct',
    slug: 'code-of-conduct',
    content: '<h2>Expected Behavior</h2><p>We are committed to providing a welcoming and inclusive environment for everyone. All team members are expected to be respectful in all interactions, whether in Slack, video calls, code reviews, or in-person gatherings. Constructive disagreement is healthy and encouraged — personal attacks are not.</p><h2>Reporting Concerns</h2><p>If you experience or witness behavior that violates this code, report it to your manager, Hannah Foster (People Ops), or use the anonymous reporting form linked in the HR portal. All reports are investigated promptly and confidentially.</p><h2>Consequences</h2><p>Violations are addressed proportionally: coaching for minor issues, formal warnings for repeated behavior, and termination for severe violations. We believe in giving people a chance to grow, but we will not compromise the safety of our team.</p>',
    category: 'handbook',
    tags: ['handbook', 'conduct', 'hr', 'policies'],
    type: 'COMPANY_WIKI',
    createdByKey: 'hannah-foster',
    parentKey: 'handbook-section',
    isSection: false,
    daysAgo: 170,
    updatedDaysAgo: 170,
  },
  {
    key: 'remote-work',
    title: 'Remote Work Guidelines',
    slug: 'remote-work-guidelines',
    content: '<h2>Work Location</h2><p>Acme is a remote-first company. Most of the team works from home, and we have a small office in San Francisco for those who prefer in-person work. There is no expectation to come to the office, but it\'s available Monday through Friday.</p><h2>Core Hours</h2><p>We have core collaboration hours from 10am to 2pm Pacific Time. During these hours, you should be available for synchronous communication. Outside of core hours, work whenever you\'re most productive. We trust you to manage your schedule.</p><h2>Communication Norms</h2><p>Default to async. Write things down in wiki pages or Slack threads instead of scheduling meetings. When you do need a meeting, keep it to 25 or 50 minutes and always include an agenda. Camera-on is encouraged but never required.</p><h2>In-Person Gatherings</h2><p>We hold a company offsite twice a year (typically January and July) in different cities. These are focused on team building, strategic planning, and having fun together. Attendance is strongly encouraged but not mandatory.</p>',
    category: 'handbook',
    tags: ['handbook', 'remote', 'communication', 'culture'],
    type: 'COMPANY_WIKI',
    createdByKey: 'rachel-green',
    parentKey: 'handbook-section',
    isSection: false,
    daysAgo: 160,
    updatedDaysAgo: 40,
  },
  {
    key: 'onboarding-checklist',
    title: 'New Employee Onboarding Checklist',
    slug: 'onboarding-checklist',
    content: '<h2>Before Day 1</h2><p>Your manager will send you a welcome email with login credentials for Google Workspace, Slack, and GitHub. Hannah from People Ops will ship your equipment and schedule your onboarding buddy pairing. Please complete the tax forms and direct deposit setup in the HR portal before your first day.</p><h2>Week 1</h2><p>Your first week is about getting oriented. You\'ll have 1:1s with your manager, your onboarding buddy, and key cross-functional partners. By Friday, you should have your development environment set up, access to all relevant repositories, and a clear list of your first-month goals.</p><h2>First 30 Days</h2><p>Ship something real. Every new engineer ships a production change in their first two weeks — even if it\'s small. Product and design team members deliver their first artifact (spec, mockup, or user research report) within 30 days. The goal is to build confidence and establish your working rhythm.</p><h2>90-Day Check-In</h2><p>At the 90-day mark, you\'ll have a structured check-in with your manager to review progress, discuss feedback, and set goals for the next quarter. This is also when we finalize your onboarding and remove training-wheels permissions.</p>',
    category: 'handbook',
    tags: ['handbook', 'onboarding', 'new-hire'],
    type: 'COMPANY_WIKI',
    createdByKey: 'hannah-foster',
    parentKey: 'handbook-section',
    isSection: false,
    daysAgo: 140,
    updatedDaysAgo: 20,
  },
  {
    key: 'org-chart-guide',
    title: 'Org Structure & Reporting',
    slug: 'org-structure-reporting',
    content: '<h2>Company Structure</h2><p>Acme is organized into four departments: Engineering, Product & Design, Go-to-Market, and Operations. Each department is led by a head who reports directly to Sarah (CEO). Within Engineering, we have three teams: Backend, Frontend, and DevOps.</p><h2>Reporting Lines</h2><p>Every team member has a direct manager who is responsible for career development, performance reviews, and day-to-day support. Cross-functional project work is common — you might be assigned to a project led by someone outside your reporting chain. Your manager remains your primary advocate regardless of project assignment.</p><h2>Decision Making</h2><p>We use a DACI framework for significant decisions. The Driver runs the process, the Approver makes the final call, Contributors provide input, and Informed parties are kept in the loop. For most day-to-day decisions, the person closest to the problem decides.</p>',
    category: 'handbook',
    tags: ['handbook', 'org-structure', 'reporting', 'daci'],
    type: 'COMPANY_WIKI',
    createdByKey: 'sarah-chen',
    parentKey: 'handbook-section',
    isSection: false,
    daysAgo: 175,
    updatedDaysAgo: 15,
  },

  // ═══════════════════════════════════════════════════════════
  // ENGINEERING DOCS (12 pages)
  // ═══════════════════════════════════════════════════════════
  {
    key: 'eng-section',
    title: 'Engineering Documentation',
    slug: 'engineering-docs',
    content: '<h1>Engineering Documentation</h1><p>Technical documentation for the Acme Analytics engineering team. Covers architecture, development practices, deployment, and operational procedures. All engineers are expected to keep these docs up to date as part of their work.</p>',
    category: 'engineering',
    tags: ['engineering', 'docs'],
    type: 'TEAM_DOC',
    createdByKey: 'marcus-rodriguez',
    parentKey: null,
    isSection: true,
    daysAgo: 170,
    updatedDaysAgo: 5,
  },
  {
    key: 'architecture-overview',
    title: 'System Architecture Overview',
    slug: 'system-architecture-overview',
    content: '<h2>High-Level Architecture</h2><p>Acme Analytics follows a modular monolith architecture deployed on AWS. The application is built with Next.js 15 (App Router) for the frontend and API layer, PostgreSQL as the primary database, and Redis for caching and real-time features. We use Prisma as our ORM and deploy via GitHub Actions to ECS Fargate.</p><h2>Data Pipeline</h2><p>Customer data flows through a three-stage pipeline: ingestion (connectors pull data from customer sources), transformation (SQL-based transform layer that normalizes schemas), and serving (pre-computed aggregations stored in materialized views for fast chart rendering). The pipeline processes approximately 2 billion rows per day across all customers.</p><h2>Key Design Decisions</h2><p>We chose a modular monolith over microservices because at our scale (20 people, ~100 enterprise customers), the operational complexity of microservices isn\'t justified. Each module (auth, connectors, charts, sharing) has clear boundaries and could be extracted later if needed. This gives us the deployment simplicity of a monolith with the code organization of services.</p><p>PostgreSQL with pgvector handles both relational data and vector embeddings for our AI features. We considered a separate vector database but the operational overhead wasn\'t worth it for our current embedding volume (~10M vectors).</p>',
    category: 'engineering',
    tags: ['architecture', 'engineering', 'infrastructure'],
    type: 'TEAM_DOC',
    createdByKey: 'marcus-rodriguez',
    parentKey: 'eng-section',
    isSection: false,
    daysAgo: 165,
    updatedDaysAgo: 14,
  },
  {
    key: 'api-auth-guide',
    title: 'API Authentication Guide',
    slug: 'api-authentication-guide',
    content: '<h2>Authentication Methods</h2><p>Acme supports three authentication methods: session-based auth for the web app (NextAuth.js with JWT), API keys for programmatic access, and OAuth 2.0 for third-party integrations. All API requests must include authentication — unauthenticated requests receive a 401 response.</p><h2>API Keys</h2><p>API keys are scoped to a workspace and carry the permissions of the user who created them. Keys can be created in Settings → API Keys. Each key has a prefix (ak_live_ for production, ak_test_ for sandbox) and should be passed in the Authorization header as a Bearer token. Keys can be rotated without downtime — the old key remains valid for 24 hours after rotation.</p><h2>Rate Limiting</h2><p>API endpoints are rate-limited to 100 requests per minute per API key for standard plans and 1000 requests per minute for enterprise plans. Rate limit headers (X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset) are included in every response. When the limit is exceeded, the API returns 429 Too Many Requests.</p>',
    category: 'engineering',
    tags: ['api', 'authentication', 'security'],
    type: 'TEAM_DOC',
    createdByKey: 'james-kim',
    parentKey: 'eng-section',
    isSection: false,
    daysAgo: 140,
    updatedDaysAgo: 25,
  },
  {
    key: 'deployment-runbook',
    title: 'Deployment Runbook',
    slug: 'deployment-runbook',
    content: '<h2>Deployment Process</h2><p>We deploy to production on every merge to main, typically 3-5 times per day. The pipeline runs: lint → typecheck → unit tests → build → integration tests → deploy to staging → smoke tests → promote to production. The entire pipeline takes about 12 minutes. If any step fails, the deploy is halted and the team is notified in #deploys.</p><h2>Rollback Procedure</h2><p>If a production issue is detected after deploy, revert the PR on GitHub and merge the revert. This triggers a new deploy with the previous code. For database migrations that can\'t be easily reverted, contact Marcus or Alex before rolling back. We keep the last 10 deploy artifacts in S3 for emergency rollbacks.</p><h2>Feature Flags</h2><p>New features that aren\'t ready for all users should be behind feature flags. We use a simple feature flag system stored in the database (FeatureFlag model). Flags can be toggled per workspace, per user, or globally. Engineering and product managers can toggle flags in the admin panel without a deploy.</p>',
    category: 'engineering',
    tags: ['deployment', 'devops', 'runbook'],
    type: 'TEAM_DOC',
    createdByKey: 'alex-patel',
    parentKey: 'eng-section',
    isSection: false,
    daysAgo: 130,
    updatedDaysAgo: 7,
  },
  {
    key: 'db-conventions',
    title: 'Database Conventions',
    slug: 'database-conventions',
    content: '<h2>Schema Conventions</h2><p>All tables must have: id (CUID primary key), workspaceId (foreign key to workspace for multi-tenancy), createdAt, and updatedAt. Use snake_case for column names in SQL and camelCase in Prisma. Every foreign key must have an explicit onDelete behavior — prefer Cascade for workspace-scoped data and SetNull for optional references.</p><h2>Migrations</h2><p>Always use prisma migrate dev to create migration files. Never use db push in development — it skips migration file creation and causes drift between environments. Test migrations on a copy of the staging database before merging. Destructive migrations (dropping columns, changing types) require explicit approval from Marcus.</p><h2>Performance Guidelines</h2><p>Add indexes for any column used in WHERE clauses that filter more than 1000 rows. Use composite indexes for queries that filter on multiple columns (e.g., workspaceId + status). Monitor slow queries in Datadog — anything over 100ms should be investigated. Use EXPLAIN ANALYZE to verify index usage before and after changes.</p>',
    category: 'engineering',
    tags: ['database', 'prisma', 'conventions'],
    type: 'TEAM_DOC',
    createdByKey: 'james-kim',
    parentKey: 'eng-section',
    isSection: false,
    daysAgo: 155,
    updatedDaysAgo: 30,
  },
  {
    key: 'code-review-standards',
    title: 'Code Review Standards',
    slug: 'code-review-standards',
    content: '<h2>Review Expectations</h2><p>Every PR requires at least one approval before merging. For changes touching auth, billing, or data pipeline code, two approvals are required. Reviewers should respond within 4 business hours — if you can\'t review in time, reassign or comment that you\'ll be delayed. The goal is to never block someone for more than a day.</p><h2>What to Look For</h2><p>Focus your review on: correctness (does it do what it claims?), security (any SQL injection, XSS, or auth bypass risks?), performance (any N+1 queries or missing indexes?), and maintainability (will someone else understand this in 6 months?). Style nits should be handled by the linter, not by reviewers.</p><h2>PR Size</h2><p>Keep PRs under 400 lines of changed code. Larger changes should be broken into a stack of smaller PRs. If a large PR is unavoidable, add a PR description that explains the overall approach and guides reviewers through the changes in a logical order. Use draft PRs for work-in-progress that you want early feedback on.</p>',
    category: 'engineering',
    tags: ['code-review', 'engineering', 'process'],
    type: 'TEAM_DOC',
    createdByKey: 'marcus-rodriguez',
    parentKey: 'eng-section',
    isSection: false,
    daysAgo: 160,
    updatedDaysAgo: 45,
  },
  {
    key: 'incident-response',
    title: 'Incident Response Playbook',
    slug: 'incident-response-playbook',
    content: '<h2>Severity Levels</h2><p>SEV1: Complete outage affecting all customers. Response time: 15 minutes. SEV2: Partial outage or degraded performance affecting >10% of customers. Response time: 1 hour. SEV3: Minor issue affecting a small number of customers. Response time: 4 hours. SEV4: Cosmetic or low-impact issue. Response time: next business day.</p><h2>Incident Commander</h2><p>The on-call engineer is the default incident commander for SEV1 and SEV2 incidents. They own the response: coordinating the team, communicating status updates to stakeholders, and writing the post-incident review. The current on-call rotation is Alex Patel (primary) and James Kim (secondary).</p><h2>Post-Incident Review</h2><p>Every SEV1 and SEV2 incident gets a post-incident review within 48 hours. The review is blameless and focuses on: what happened, why our systems didn\'t prevent it, and what we\'re changing to prevent recurrence. Reviews are published in #incidents and linked from this page.</p>',
    category: 'engineering',
    tags: ['incidents', 'on-call', 'devops', 'playbook'],
    type: 'TEAM_DOC',
    createdByKey: 'alex-patel',
    parentKey: 'eng-section',
    isSection: false,
    daysAgo: 120,
    updatedDaysAgo: 10,
  },
  {
    key: 'monitoring-guide',
    title: 'Monitoring & Alerting Guide',
    slug: 'monitoring-alerting-guide',
    content: '<h2>Monitoring Stack</h2><p>We use Datadog for infrastructure monitoring, application performance monitoring (APM), and log aggregation. Sentry handles error tracking with source maps for frontend errors. PagerDuty routes alerts to the on-call engineer based on severity and team ownership.</p><h2>Key Dashboards</h2><p>The main production dashboard shows: API request rate and latency (P50, P95, P99), error rate by endpoint, database connection pool usage, Redis cache hit rate, and ECS task health. Each team also maintains their own dashboards: Backend has a query performance dashboard, Frontend has a Core Web Vitals dashboard, and DevOps has an infrastructure cost dashboard.</p><h2>Alert Thresholds</h2><p>Critical alerts (wake people up): API error rate > 5% for 5 minutes, P99 latency > 2 seconds for 10 minutes, database connection pool > 90% for 5 minutes. Warning alerts (Slack notification): API error rate > 1% for 10 minutes, P99 latency > 1 second for 15 minutes, disk usage > 80%. All alerts include a runbook link explaining what to check and how to remediate.</p>',
    category: 'engineering',
    tags: ['monitoring', 'datadog', 'alerting', 'devops'],
    type: 'TEAM_DOC',
    createdByKey: 'alex-patel',
    parentKey: 'eng-section',
    isSection: false,
    daysAgo: 110,
    updatedDaysAgo: 8,
  },
  {
    key: 'cicd-pipeline',
    title: 'CI/CD Pipeline Configuration',
    slug: 'cicd-pipeline-configuration',
    content: '<h2>GitHub Actions Workflows</h2><p>Our CI pipeline runs on every push to a PR branch and on merge to main. The PR pipeline runs lint, typecheck, unit tests, and builds the application. The merge pipeline extends this with integration tests, Docker image build, and deployment to staging. Promotion to production requires a manual approval in the GitHub Actions UI for changes that include database migrations.</p><h2>Environment Configuration</h2><p>We maintain three environments: development (local), staging (staging.acme-analytics.com), and production (app.acme-analytics.com). Each environment has its own database, Redis instance, and secrets. Environment variables are managed through AWS Systems Manager Parameter Store and injected at deploy time.</p><h2>Caching Strategy</h2><p>The CI pipeline caches node_modules (keyed on package-lock.json hash), Prisma client (keyed on schema hash), and Next.js build cache (keyed on source hash). This reduces build times from ~8 minutes to ~4 minutes on cache hit. Cache is invalidated weekly to prevent stale dependency issues.</p>',
    category: 'engineering',
    tags: ['ci-cd', 'github-actions', 'devops'],
    type: 'TEAM_DOC',
    createdByKey: 'alex-patel',
    parentKey: 'eng-section',
    isSection: false,
    daysAgo: 125,
    updatedDaysAgo: 18,
  },
  {
    key: 'testing-strategy',
    title: 'Testing Strategy',
    slug: 'testing-strategy',
    content: '<h2>Testing Pyramid</h2><p>Our testing strategy follows the testing pyramid: many unit tests, a moderate number of integration tests, and a few end-to-end tests. Unit tests use Vitest and should cover all business logic and utility functions. Integration tests verify API routes with a real database (test container). E2E tests use Playwright and cover critical user journeys.</p><h2>Coverage Expectations</h2><p>We target 80% code coverage for business logic modules and 60% for API routes. Frontend components should have tests for interactive behavior (clicks, form submissions) but not for static rendering. Coverage is tracked in CI but not enforced as a gate — we trust engineers to test what matters.</p><h2>Test Data</h2><p>Integration tests use factory functions to create test data. Each test creates its own workspace and users to avoid interference between tests. Use the test helpers in src/test/factories/ for creating common entities. Never use production data in tests — generate realistic but synthetic data using the factory functions.</p>',
    category: 'engineering',
    tags: ['testing', 'vitest', 'playwright', 'engineering'],
    type: 'TEAM_DOC',
    createdByKey: 'james-kim',
    parentKey: 'eng-section',
    isSection: false,
    daysAgo: 135,
    updatedDaysAgo: 22,
  },
  {
    key: 'dev-env-setup',
    title: 'Development Environment Setup',
    slug: 'dev-environment-setup',
    content: '<h2>Prerequisites</h2><p>You need Node.js 20+, PostgreSQL 15+, Redis 7+, and Git. We recommend using nvm for Node version management and Docker for PostgreSQL and Redis. Clone the repo, copy .env.example to .env.local, and run npm install followed by npx prisma migrate dev.</p><h2>Running Locally</h2><p>Start the dev server with npm run dev (port 3000). The app uses Turbopack for fast refresh — changes to React components are reflected in under 100ms. For testing the real-time collaboration features, you\'ll also need to run npm run dev:collab in a separate terminal.</p><h2>Common Issues</h2><p>If you see Prisma schema errors after pulling, run npx prisma generate to regenerate the client. If the database is out of sync, run npx prisma migrate dev to apply pending migrations. For port conflicts, use npm run dev:free-port to kill any process on port 3000. If the build fails with memory errors, increase Node\'s heap size with NODE_OPTIONS="--max-old-space-size=4096".</p>',
    category: 'engineering',
    tags: ['setup', 'development', 'getting-started'],
    type: 'TEAM_DOC',
    createdByKey: 'marcus-rodriguez',
    parentKey: 'eng-section',
    isSection: false,
    daysAgo: 168,
    updatedDaysAgo: 3,
  },
  {
    key: 'security-practices',
    title: 'Security Best Practices',
    slug: 'security-best-practices',
    content: '<h2>Authentication & Authorization</h2><p>Every API route must call getUnifiedAuth() for authentication and assertAccess() for authorization. No exceptions. The middleware layer handles route protection, but API routes must verify permissions at the resource level. Use the role hierarchy (VIEWER < MEMBER < ADMIN < OWNER) for access control decisions.</p><h2>Data Security</h2><p>Customer data is encrypted at rest (AES-256) and in transit (TLS 1.3). Database credentials are rotated quarterly and stored in AWS Secrets Manager. API keys are hashed with bcrypt before storage — we never store plaintext keys. PII fields are flagged in the Prisma schema and excluded from logging.</p><h2>Dependency Security</h2><p>npm audit runs on every PR and blocks merges for high-severity vulnerabilities. We use Dependabot for automated dependency updates and review security advisories weekly. Third-party packages must be evaluated for maintenance status and security posture before adoption.</p>',
    category: 'engineering',
    tags: ['security', 'auth', 'engineering', 'compliance'],
    type: 'TEAM_DOC',
    createdByKey: 'james-kim',
    parentKey: 'eng-section',
    isSection: false,
    daysAgo: 100,
    updatedDaysAgo: 12,
  },

  // ═══════════════════════════════════════════════════════════
  // PRODUCT SPECS (10 pages)
  // ═══════════════════════════════════════════════════════════
  {
    key: 'product-section',
    title: 'Product Specifications',
    slug: 'product-specs',
    content: '<h1>Product Specifications</h1><p>Product requirement documents, user stories, and research findings for Acme Analytics features. Each spec follows our PRD template and includes user stories, success metrics, and technical considerations.</p>',
    category: 'product',
    tags: ['product', 'specs'],
    type: 'PROJECT_DOC',
    createdByKey: 'emma-thompson',
    parentKey: null,
    isSection: true,
    daysAgo: 160,
    updatedDaysAgo: 5,
  },
  {
    key: 'prd-enterprise-dashboard',
    title: 'PRD: Enterprise Dashboard Features',
    slug: 'prd-enterprise-dashboard',
    content: '<h2>Problem Statement</h2><p>Enterprise customers (50+ seats) need workspace-level access controls, audit logging, and SSO integration before they can adopt Acme. Three deals totaling $450K ARR are blocked on these features. Without them, we lose to Tableau and Looker in enterprise evaluations.</p><h2>User Stories</h2><p>As a workspace admin, I want to assign roles (Viewer, Editor, Admin) to team members so that I can control who can modify dashboards and data connections. As a security officer, I want an audit log of all admin actions so that I can demonstrate compliance during security reviews. As an IT admin, I want to configure SAML SSO so that employees can use their corporate credentials to access Acme.</p><h2>Success Metrics</h2><p>Close 3 enterprise deals within 60 days of launch. Achieve SOC 2 Type II readiness. Zero security incidents related to access control in the first 90 days.</p><h2>Technical Approach</h2><p>RBAC will extend the existing WorkspaceMember role system. Audit logging will use an append-only events table with immutable records. SSO will integrate with the NextAuth.js SAML provider. Enterprise features will be gated behind a subscription tier check.</p>',
    category: 'product',
    tags: ['prd', 'enterprise', 'rbac', 'sso'],
    type: 'PROJECT_DOC',
    createdByKey: 'raj-krishnamurthy',
    parentKey: 'product-section',
    isSection: false,
    daysAgo: 50,
    updatedDaysAgo: 8,
  },
  {
    key: 'prd-onboarding-automation',
    title: 'PRD: Customer Onboarding Automation',
    slug: 'prd-onboarding-automation',
    content: '<h2>Problem Statement</h2><p>New customers take an average of 14 days to reach their "aha moment" (creating their first shared dashboard). 30% of trial users never connect a data source. Manual onboarding by the CS team doesn\'t scale beyond 50 new accounts per month.</p><h2>Proposed Solution</h2><p>A guided setup wizard that walks new users through: connecting their first data source (with pre-built connectors for popular databases), creating their first chart (with suggested visualizations based on their data schema), and sharing their first dashboard (with one-click team invite). Automated email sequences nudge users who stall at each step.</p><h2>Success Metrics</h2><p>Reduce median time-to-value from 14 days to 3 days. Increase trial-to-paid conversion from 12% to 20%. Reduce CS team onboarding hours by 60%.</p><h2>Out of Scope</h2><p>Custom onboarding flows per customer segment (Phase 2). White-glove enterprise onboarding remains manual for now. Mobile onboarding is not included in this phase.</p>',
    category: 'product',
    tags: ['prd', 'onboarding', 'automation', 'customer-success'],
    type: 'PROJECT_DOC',
    createdByKey: 'olivia-park',
    parentKey: 'product-section',
    isSection: false,
    daysAgo: 35,
    updatedDaysAgo: 12,
  },
  {
    key: 'prd-website-redesign',
    title: 'PRD: Marketing Website Redesign',
    slug: 'prd-marketing-website-redesign',
    content: '<h2>Problem Statement</h2><p>Our current website converts visitors to demo requests at 2%, well below the industry average of 4-5% for B2B SaaS. The design is outdated, mobile experience is poor, and there are no interactive product demos. Competitors like Hex and Mode have modern, engaging marketing sites that communicate value in seconds.</p><h2>Goals</h2><p>Increase demo request rate to 5%. Improve mobile page speed score to 90+. Launch interactive product demo that visitors can try without signing up. Refresh brand identity to reflect our position as a modern, developer-friendly analytics tool.</p><h2>Key Pages</h2><p>Homepage (hero with interactive demo, customer logos, feature highlights, pricing CTA). Product page (detailed feature breakdown with screenshots). Pricing page (transparent pricing with feature comparison). Case studies (3 customer stories with metrics). Blog (SEO-optimized content hub).</p>',
    category: 'product',
    tags: ['prd', 'marketing', 'website', 'conversion'],
    type: 'PROJECT_DOC',
    createdByKey: 'megan-obrien',
    parentKey: 'product-section',
    isSection: false,
    daysAgo: 18,
    updatedDaysAgo: 6,
  },
  {
    key: 'product-roadmap',
    title: 'Product Roadmap — 2026',
    slug: 'product-roadmap-2026',
    content: '<h2>Q1 (Jan–Mar): Foundation</h2><p>GA launch of core dashboard product. PostgreSQL and Snowflake connectors. Basic sharing and collaboration. 50 beta customers migrated to production. Status: COMPLETED.</p><h2>Q2 (Apr–Jun): Enterprise</h2><p>RBAC and permissions system. SAML SSO integration. Audit logging and compliance features. Advanced charts (pivot tables, geo maps). Target: 3 enterprise deals closed. Status: IN PROGRESS.</p><h2>Q3 (Jul–Sep): Growth</h2><p>Customer onboarding automation. Marketing website redesign. Self-serve trial with no credit card. BigQuery and Redshift connectors. Target: 100 paying customers. Status: PLANNING.</p><h2>Q4 (Oct–Dec): Scale</h2><p>Real-time dashboards with live data refresh. Embedded analytics (white-label charts in customer apps). API v2 with webhook subscriptions. Mobile-responsive dashboard viewer. Target: $1M ARR. Status: PLANNING.</p>',
    category: 'product',
    tags: ['roadmap', 'product', 'strategy', '2026'],
    type: 'COMPANY_WIKI',
    createdByKey: 'emma-thompson',
    parentKey: 'product-section',
    isSection: false,
    daysAgo: 90,
    updatedDaysAgo: 3,
  },
  {
    key: 'competitive-analysis',
    title: 'Competitive Landscape Analysis',
    slug: 'competitive-landscape-analysis',
    content: '<h2>Direct Competitors</h2><p><strong>Tableau:</strong> The incumbent. Powerful but complex. Requires training to use effectively. Pricing starts at $70/user/month. Weak on collaboration and real-time data. Our advantage: simplicity and modern UX.</p><p><strong>Looker (Google):</strong> Strong data modeling layer (LookML) but steep learning curve. Tied to Google Cloud. Enterprise-focused pricing. Our advantage: database-agnostic, faster time to first chart.</p><p><strong>Mode:</strong> Good SQL-first analytics for data teams. Weak on self-serve for business users. Our advantage: drag-and-drop interface that doesn\'t require SQL knowledge.</p><h2>Adjacent Competitors</h2><p><strong>Hex:</strong> Notebook-style analytics, very developer-friendly. Less suited for traditional dashboards. <strong>Metabase:</strong> Open-source, easy setup, but limited enterprise features. <strong>Preset (Superset):</strong> Open-source managed service, good for engineering-led organizations.</p><h2>Our Positioning</h2><p>Acme Analytics is the modern data visualization tool that\'s as easy as a spreadsheet but as powerful as Tableau. We target mid-market companies (50-500 employees) that have outgrown Google Sheets but don\'t want to hire a BI team.</p>',
    category: 'product',
    tags: ['competitive', 'strategy', 'market'],
    type: 'COMPANY_WIKI',
    createdByKey: 'emma-thompson',
    parentKey: 'product-section',
    isSection: false,
    daysAgo: 100,
    updatedDaysAgo: 20,
  },
  {
    key: 'user-research-q1',
    title: 'User Research Findings — Q1 2026',
    slug: 'user-research-q1-2026',
    content: '<h2>Methodology</h2><p>We conducted 15 user interviews (8 existing customers, 7 prospects) and ran a 500-person survey across our newsletter audience. Interviews were 45 minutes each, recorded with permission, and analyzed using affinity mapping.</p><h2>Key Findings</h2><p><strong>Finding 1: Time to first chart is the #1 predictor of retention.</strong> Users who create their first chart within 24 hours of signing up are 4x more likely to become paying customers. The current median is 4 days, dragged up by the data connection step.</p><p><strong>Finding 2: Sharing is the growth loop.</strong> 70% of new signups come from receiving a shared dashboard link. But 40% of those visitors bounce because they\'re asked to create an account before seeing the dashboard. We need a view-only mode for shared links.</p><p><strong>Finding 3: Enterprise buyers need proof of security.</strong> Every enterprise prospect asked about SOC 2, SSO, and audit logging in their first call. Three deals worth $450K are explicitly blocked on RBAC and SSO. This aligns with the Enterprise Dashboard project scope.</p>',
    category: 'product',
    tags: ['research', 'user-interviews', 'findings', 'q1'],
    type: 'PROJECT_DOC',
    createdByKey: 'olivia-park',
    parentKey: 'product-section',
    isSection: false,
    daysAgo: 45,
    updatedDaysAgo: 45,
  },
  {
    key: 'user-story-template',
    title: 'User Story Template & Guidelines',
    slug: 'user-story-template',
    content: '<h2>Template</h2><p>Use this format for all user stories: As a [user type], I want to [action] so that [benefit]. Each story should include acceptance criteria (given/when/then), edge cases, and a link to the relevant Figma designs. Stories should be small enough to complete in a single sprint.</p><h2>Definition of Ready</h2><p>A story is ready for development when it has: clear acceptance criteria, Figma designs attached (or explicitly marked as "no design needed"), technical questions resolved, and a size estimate from engineering. Stories without these elements should be flagged in sprint planning.</p><h2>Definition of Done</h2><p>A story is done when: code is merged to main, unit tests pass, the feature works in staging, QA has verified acceptance criteria, documentation is updated (if applicable), and the story is demoed in sprint review. "Done" means a customer could use it today.</p>',
    category: 'product',
    tags: ['template', 'user-stories', 'process'],
    type: 'TEAM_DOC',
    createdByKey: 'raj-krishnamurthy',
    parentKey: 'product-section',
    isSection: false,
    daysAgo: 145,
    updatedDaysAgo: 60,
  },
  {
    key: 'prd-sales-enablement',
    title: 'PRD: Sales Enablement Platform',
    slug: 'prd-sales-enablement',
    content: '<h2>Problem Statement</h2><p>The sales team manages deals in spreadsheets, competitive intel lives in scattered Google Docs, and proposal creation is a manual copy-paste process that takes 2-3 hours per deal. As we scale from 3 to 10 AEs, this workflow won\'t hold up. We need a centralized tool that gives the sales team a single source of truth.</p><h2>Proposed Solution</h2><p>An internal sales enablement platform with three modules: Deal Tracker (Kanban board synced with Salesforce), Content Hub (battlecards, case studies, and pricing guides), and Proposal Generator (templated PDF proposals populated from deal data). MVP focuses on deal tracking and battlecards; proposal generation is Phase 2.</p><h2>Current Status</h2><p>This project is ON HOLD. The Salesforce integration is blocked on API access — we\'re waiting for Salesforce to provision our Connected App. Estimated unblock: 2-3 weeks. In the meantime, the team is building the content hub with manual data entry.</p>',
    category: 'product',
    tags: ['prd', 'sales', 'enablement', 'blocked'],
    type: 'PROJECT_DOC',
    createdByKey: 'olivia-park',
    parentKey: 'product-section',
    isSection: false,
    daysAgo: 55,
    updatedDaysAgo: 15,
  },

  // ═══════════════════════════════════════════════════════════
  // MEETING NOTES (10 pages)
  // ═══════════════════════════════════════════════════════════
  {
    key: 'meetings-section',
    title: 'Meeting Notes',
    slug: 'meeting-notes',
    content: '<h1>Meeting Notes</h1><p>Notes from recurring team meetings, all-hands, and planning sessions. Meeting notes should be published within 24 hours of the meeting. If you missed a meeting, read the notes before asking someone to recap.</p>',
    category: 'meetings',
    tags: ['meetings', 'notes'],
    type: 'TEAM_DOC',
    createdByKey: 'emma-thompson',
    parentKey: null,
    isSection: true,
    daysAgo: 170,
    updatedDaysAgo: 2,
  },
  {
    key: 'sprint-planning-23',
    title: 'Sprint 23 Planning Notes',
    slug: 'sprint-23-planning',
    content: '<h2>Sprint 23 (Feb 17 – Mar 2)</h2><p>Attendees: Marcus, James, Lisa, Priya, Noah, Tyler, Maria, Fatima, Alex</p><h2>Sprint Goals</h2><p>1. Complete RBAC permission model (James — carry over from Sprint 22). 2. Start SAML SSO implementation (Noah). 3. Pivot table component MVP (Tyler). 4. Onboarding wizard API endpoints (Priya).</p><h2>Capacity Notes</h2><p>Lisa is at 60% capacity this sprint due to conference speaking prep. Alex is splitting time between Enterprise Dashboard (staging env) and production monitoring improvements. Fatima will start on audit logging after ramping up on the codebase.</p><h2>Risks</h2><p>SAML SSO has unknown complexity — Noah hasn\'t worked with SAML before. Mitigation: James will pair with Noah for the first 2 days. Pivot table performance with large datasets is a concern — Tyler will benchmark with 100K row datasets before the design review.</p>',
    category: 'meetings',
    tags: ['sprint', 'planning', 'engineering'],
    type: 'TEAM_DOC',
    createdByKey: 'marcus-rodriguez',
    parentKey: 'meetings-section',
    isSection: false,
    daysAgo: 14,
    updatedDaysAgo: 14,
  },
  {
    key: 'sprint-retro-22',
    title: 'Sprint 22 Retrospective',
    slug: 'sprint-22-retrospective',
    content: '<h2>Sprint 22 Retrospective (Feb 14)</h2><p>Facilitator: Lisa Zhang. Attendees: Engineering team (9 people).</p><h2>What Went Well</h2><p>Staging environment for enterprise testing was set up quickly (Alex, 2 days instead of estimated 5). Design for RBAC management UI was finalized ahead of schedule (Daniel). Maria shipped the pricing page component library ahead of estimate.</p><h2>What Could Be Better</h2><p>RBAC permission model is taking longer than estimated — the interaction between workspace roles and resource-level permissions is more complex than anticipated. We underestimated by 5 points. Sprint velocity was lower than average (38 vs 45) due to unplanned production incident on Feb 10.</p><h2>Action Items</h2><p>1. Break down complex backend tasks more aggressively — no single task should be > 8 points (James). 2. Add integration tests for permission edge cases before marking RBAC as done (Priya). 3. Schedule a "SAML SSO deep dive" session before Sprint 23 starts (Marcus + Noah).</p>',
    category: 'meetings',
    tags: ['sprint', 'retrospective', 'engineering'],
    type: 'TEAM_DOC',
    createdByKey: 'lisa-zhang',
    parentKey: 'meetings-section',
    isSection: false,
    daysAgo: 17,
    updatedDaysAgo: 17,
  },
  {
    key: 'all-hands-feb',
    title: 'All-Hands Meeting — February 2026',
    slug: 'all-hands-february-2026',
    content: '<h2>February All-Hands (Feb 7, 2026)</h2><p>Presenter: Sarah Chen. All 20 team members in attendance.</p><h2>Company Update</h2><p>We closed January with $320K ARR, up 15% from December. 87 paying customers, 12 on enterprise plans. Runway is 18 months at current burn rate. The Q1 Product Launch was completed successfully — all 50 beta customers migrated to production with zero data loss.</p><h2>Hiring Update</h2><p>We have two open roles: Senior Frontend Engineer (to support the growing chart library) and Sales Development Representative (to feed the AE pipeline). Referral bonus is $5,000 for engineering and $3,000 for sales. Talk to Hannah if you know someone.</p><h2>Spotlight</h2><p>Shoutout to Alex Patel for the production monitoring overhaul — our mean time to detection went from 12 minutes to 90 seconds. And to Yuki Tanaka for the "Data Visualization for Humans" blog series that drove 40% of our January inbound leads.</p><h2>Q&A Highlights</h2><p>Q: When will we support BigQuery? A: Q3 roadmap, starting July. Q: Are we planning an in-person offsite? A: Yes, July in Austin. Details coming in March.</p>',
    category: 'meetings',
    tags: ['all-hands', 'company-update', 'monthly'],
    type: 'COMPANY_WIKI',
    createdByKey: 'sarah-chen',
    parentKey: 'meetings-section',
    isSection: false,
    daysAgo: 24,
    updatedDaysAgo: 24,
  },
  {
    key: 'design-review-charts',
    title: 'Design Review: Advanced Charts',
    slug: 'design-review-advanced-charts',
    content: '<h2>Design Review — Advanced Charts (Feb 20)</h2><p>Attendees: Daniel, Sophie, Lisa, Tyler, Raj, Emma</p><h2>Pivot Table Design</h2><p>Daniel presented three options for the pivot table interaction model. Option A: spreadsheet-style with inline editing. Option B: configuration panel with preview. Option C: hybrid with drag-and-drop field wells (like Excel PivotTable). Team voted for Option C — it\'s the most intuitive for users coming from Excel. Tyler raised a concern about drag-and-drop performance with many fields; agreed to cap at 50 fields initially.</p><h2>Geo Map Design</h2><p>Sophie showed the choropleth map concept with a stepped color scale. Feedback: need to support both continuous and discrete color scales. Lisa suggested using MapboxGL for rendering — she has experience from her Observable days. Decision: MapboxGL for MVP, consider deck.gl for 3D visualizations later.</p><h2>Next Steps</h2><p>Daniel will finalize high-fidelity mocks by Feb 28. Tyler will build a pivot table prototype in Storybook by March 5. Lisa will evaluate MapboxGL bundle size impact.</p>',
    category: 'meetings',
    tags: ['design-review', 'charts', 'product'],
    type: 'TEAM_DOC',
    createdByKey: 'daniel-nakamura',
    parentKey: 'meetings-section',
    isSection: false,
    daysAgo: 11,
    updatedDaysAgo: 11,
  },
  {
    key: 'one-on-one-template',
    title: '1:1 Meeting Template',
    slug: 'one-on-one-template',
    content: '<h2>1:1 Meeting Template</h2><p>Use this template for all manager-report 1:1s. Meetings should be 30 minutes, weekly, and should not be cancelled more than once per month. The report owns the agenda — managers should ask, not tell.</p><h2>Suggested Agenda</h2><p><strong>Check-in (5 min):</strong> How are you doing? Anything on your mind outside of work? <strong>Updates (10 min):</strong> What did you ship this week? What are you working on next? Any blockers? <strong>Growth (10 min):</strong> What are you learning? What skill do you want to develop? How can I help? <strong>Feedback (5 min):</strong> Do you have feedback for me? Is there anything I should do differently?</p><h2>Anti-Patterns</h2><p>Don\'t use 1:1s for status updates — that\'s what standup and sprint reviews are for. Don\'t skip the growth section — it\'s the most valuable part. Don\'t let the manager do most of the talking — the report should speak 70% of the time. Don\'t cancel without rescheduling.</p>',
    category: 'meetings',
    tags: ['template', '1-1', 'management', 'meetings'],
    type: 'TEAM_DOC',
    createdByKey: 'rachel-green',
    parentKey: 'meetings-section',
    isSection: false,
    daysAgo: 155,
    updatedDaysAgo: 55,
  },
  {
    key: 'product-sync-feb24',
    title: 'Product Sync — Feb 24',
    slug: 'product-sync-feb-24',
    content: '<h2>Product Sync (Feb 24)</h2><p>Attendees: Emma, Raj, Olivia, Daniel, Sophie, Marcus</p><h2>Enterprise Dashboard Update</h2><p>RBAC permission model is in review (James). SAML SSO implementation started (Noah) — estimated 2 more weeks. Pivot table component is progressing well (Tyler). Raj reports that two enterprise prospects (DataFlow Corp and FinServ Co) are waiting on RBAC to sign. Target close: end of March.</p><h2>Onboarding Automation Update</h2><p>User research complete — 14-day time-to-value confirmed as the critical metric. Wizard flow designed and approved. Backend API in progress (Priya). Frontend build starting this sprint (Maria). Email templates in review (Hannah). On track for April launch.</p><h2>Marketing Website</h2><p>Brand audit complete (Sophie). Wireframes for homepage in progress (Daniel). Yuki is writing case studies. Megan is planning the product demo video. Targeting late March for design approval, April for development, May for launch.</p><h2>Sales Enablement</h2><p>Still blocked on Salesforce API access. David is escalating through our Salesforce account manager. Content hub work continues in parallel. Revised ETA: unblock in 2-3 weeks.</p>',
    category: 'meetings',
    tags: ['product-sync', 'weekly', 'status'],
    type: 'TEAM_DOC',
    createdByKey: 'emma-thompson',
    parentKey: 'meetings-section',
    isSection: false,
    daysAgo: 7,
    updatedDaysAgo: 7,
  },
  {
    key: 'eng-standup-summary',
    title: 'Engineering Standup Summary — Week of Feb 24',
    slug: 'eng-standup-week-feb-24',
    content: '<h2>Monday</h2><p>James: RBAC PR submitted for review, addressing feedback on edge cases. Priya: onboarding progress API at 70%, working on webhook notifications. Noah: SAML SSO — studying the SAML 2.0 spec, will start implementation Tuesday. Tyler: pivot table drag-and-drop working for rows, starting columns. Alex: staging env stable, switching to monitoring dashboard improvements.</p><h2>Wednesday</h2><p>James: RBAC approved with minor changes, merging today. Priya: webhook notifications working, moving to integration tests. Noah: SAML basic flow working with test IdP, need to handle edge cases (multi-tenant, group mapping). Tyler: pivot table columns working, aggregation functions in progress. Lisa: evaluating MapboxGL — bundle adds 200KB gzipped, acceptable. Maria: onboarding wizard step 1 (data source connection) UI complete.</p><h2>Friday</h2><p>James: RBAC merged! Starting permission check middleware. Priya: onboarding API tests passing, moving to email trigger service. Noah: SAML working with Okta test instance, Azure AD next week. Tyler: pivot table with sum/count/avg working, performance testing Monday. Fatima: finished codebase orientation, starting audit log data model Monday. Alex: monitoring dashboards updated, starting on-call rotation automation.</p>',
    category: 'meetings',
    tags: ['standup', 'engineering', 'weekly'],
    type: 'TEAM_DOC',
    createdByKey: 'marcus-rodriguez',
    parentKey: 'meetings-section',
    isSection: false,
    daysAgo: 3,
    updatedDaysAgo: 3,
  },
  {
    key: 'sales-pipeline-review',
    title: 'Sales Pipeline Review — February',
    slug: 'sales-pipeline-review-february',
    content: '<h2>Pipeline Review (Feb 21)</h2><p>Attendees: David, Chris, Aisha, Brandon, Sarah</p><h2>Pipeline Summary</h2><p>Total pipeline: $1.2M (up from $890K in January). 8 deals in negotiation stage, 12 in evaluation, 23 in discovery. Weighted pipeline: $480K. Q1 target: $150K new ARR. Current closed: $85K. Gap to target: $65K.</p><h2>Key Deals</h2><p><strong>DataFlow Corp ($120K ARR):</strong> Enterprise plan, 50 seats. Blocked on RBAC feature — Chris is managing expectations with a March 15 ETA. Security review scheduled for March 5. <strong>TechStart Inc ($45K ARR):</strong> Mid-market, 20 seats. POC completed successfully. Contract in legal review. Expected close: March 1. <strong>FinServ Co ($85K ARR):</strong> Enterprise, 35 seats. Requires SOC 2 report — we need the compliance features from Enterprise Dashboard. Aisha is working on an interim security questionnaire response.</p><h2>Action Items</h2><p>1. Chris to send DataFlow a preview of RBAC in staging (by Feb 28). 2. Aisha to complete FinServ security questionnaire (by March 3). 3. Brandon to schedule demos for 5 discovery-stage deals (by March 7). 4. David to hire SDR — posting job req this week.</p>',
    category: 'meetings',
    tags: ['sales', 'pipeline', 'review', 'monthly'],
    type: 'TEAM_DOC',
    createdByKey: 'david-wilson',
    parentKey: 'meetings-section',
    isSection: false,
    daysAgo: 10,
    updatedDaysAgo: 10,
  },
  {
    key: 'board-meeting-q4',
    title: 'Board Meeting Notes — Q4 2025',
    slug: 'board-meeting-q4-2025',
    content: '<h2>Q4 2025 Board Meeting (Jan 15, 2026)</h2><p>Attendees: Sarah Chen (CEO), Board members (3), Kevin Nguyen (Finance)</p><h2>Financial Summary</h2><p>Q4 revenue: $75K ARR (up from $42K in Q3). Burn rate: $180K/month. Runway: 20 months. Customer count: 72 (up from 45). Net revenue retention: 115%. CAC payback: 14 months.</p><h2>Product Update</h2><p>Q1 Product Launch on track for February completion. Enterprise features (RBAC, SSO) scheduled for Q2. Three enterprise deals worth $450K ARR in pipeline contingent on these features. Board approved the product roadmap for 2026.</p><h2>Hiring Plan</h2><p>Board approved 5 new hires in H1: 2 engineers, 1 SDR, 1 AE, 1 marketing contractor. Focus on engineering to accelerate enterprise feature delivery. Total headcount will be 25 by end of H1.</p><h2>Board Feedback</h2><p>Board encouraged faster enterprise motion — the $450K pipeline is validation. Suggested exploring partnership with a system integrator for enterprise onboarding. Asked for monthly ARR update emails between board meetings.</p>',
    category: 'meetings',
    tags: ['board', 'quarterly', 'finance', 'executive'],
    type: 'COMPANY_WIKI',
    createdByKey: 'sarah-chen',
    parentKey: 'meetings-section',
    isSection: false,
    daysAgo: 47,
    updatedDaysAgo: 47,
  },

  // ═══════════════════════════════════════════════════════════
  // DESIGN SYSTEM (5 pages)
  // ═══════════════════════════════════════════════════════════
  {
    key: 'design-section',
    title: 'Design System',
    slug: 'design-system',
    content: '<h1>Acme Design System</h1><p>The Acme design system defines our visual language, component library, and design principles. All product UI should use components from this system. Custom styling should be rare and approved by the design team.</p>',
    category: 'design',
    tags: ['design', 'design-system'],
    type: 'TEAM_DOC',
    createdByKey: 'daniel-nakamura',
    parentKey: null,
    isSection: true,
    daysAgo: 140,
    updatedDaysAgo: 10,
  },
  {
    key: 'component-library',
    title: 'Component Library Documentation',
    slug: 'component-library',
    content: '<h2>Core Components</h2><p>Our component library is built on shadcn/ui with custom theming for the Acme brand. All components live in src/components/ui/ and are documented in Storybook at storybook.acme-analytics.com. Components follow the compound component pattern and use cva (class-variance-authority) for variant management.</p><h2>Key Components</h2><p><strong>Button:</strong> Four variants (primary, secondary, ghost, destructive) × three sizes (sm, md, lg). Always use the Button component instead of raw HTML buttons. <strong>Card:</strong> Container with header, body, and footer slots. Used for dashboard widgets, settings panels, and list items. <strong>DataTable:</strong> Sortable, filterable table with pagination. Supports custom cell renderers and bulk actions. <strong>Chart:</strong> Wrapper around our charting engine that handles responsive sizing, theming, and loading states.</p><h2>Usage Guidelines</h2><p>Import components from @/components/ui. Use the cn() utility for className merging. Never override component styles with inline styles — use the variant system or request a new variant from the design team. All interactive components must have appropriate aria labels and keyboard navigation.</p>',
    category: 'design',
    tags: ['components', 'shadcn', 'storybook', 'design-system'],
    type: 'TEAM_DOC',
    createdByKey: 'tyler-okonkwo',
    parentKey: 'design-section',
    isSection: false,
    daysAgo: 130,
    updatedDaysAgo: 14,
  },
  {
    key: 'color-typography',
    title: 'Color Palette & Typography',
    slug: 'color-palette-typography',
    content: '<h2>Color Palette</h2><p><strong>Primary:</strong> Blue-600 (#2563EB) for primary actions, links, and active states. <strong>Neutral:</strong> Slate scale for text, borders, and backgrounds. <strong>Success:</strong> Green-600 (#16A34A) for positive states. <strong>Warning:</strong> Amber-500 (#F59E0B) for caution states. <strong>Error:</strong> Red-600 (#DC2626) for errors and destructive actions. <strong>Chart Colors:</strong> A 12-color palette optimized for colorblind accessibility, used for data visualization series.</p><h2>Typography</h2><p><strong>Font Family:</strong> Inter for UI text, JetBrains Mono for code. Both loaded via next/font for optimal performance. <strong>Scale:</strong> xs (12px), sm (14px), base (16px), lg (18px), xl (20px), 2xl (24px), 3xl (30px). <strong>Weights:</strong> Regular (400) for body, Medium (500) for labels, Semibold (600) for headings, Bold (700) for emphasis.</p><h2>Dark Mode</h2><p>All colors have dark mode variants defined in the Tailwind config. Components automatically adapt via the dark: modifier. Test all new UI in both light and dark mode before merging. The theme toggle is in the top-right user menu.</p>',
    category: 'design',
    tags: ['colors', 'typography', 'design-tokens', 'design-system'],
    type: 'TEAM_DOC',
    createdByKey: 'sophie-dubois',
    parentKey: 'design-section',
    isSection: false,
    daysAgo: 135,
    updatedDaysAgo: 25,
  },
  {
    key: 'accessibility-guidelines',
    title: 'Accessibility Guidelines',
    slug: 'accessibility-guidelines',
    content: '<h2>Standards</h2><p>Acme targets WCAG 2.1 Level AA compliance. All new features must pass accessibility review before launch. Tyler Okonkwo is our accessibility champion and reviews all UI PRs for a11y compliance.</p><h2>Key Requirements</h2><p><strong>Color contrast:</strong> All text must meet 4.5:1 contrast ratio (3:1 for large text). Use the Chrome DevTools contrast checker or the axe browser extension. <strong>Keyboard navigation:</strong> All interactive elements must be reachable and operable via keyboard. Tab order must follow visual layout. Focus states must be visible. <strong>Screen readers:</strong> All images have alt text. Form inputs have associated labels. Dynamic content updates use aria-live regions. Charts include data tables as accessible alternatives.</p><h2>Testing</h2><p>Run the axe accessibility checker on every page before marking a story as done. We also run automated a11y tests in CI using @axe-core/playwright. Manual testing with VoiceOver (macOS) is required for complex interactive components like the chart builder and pivot table.</p>',
    category: 'design',
    tags: ['accessibility', 'a11y', 'wcag', 'design-system'],
    type: 'TEAM_DOC',
    createdByKey: 'tyler-okonkwo',
    parentKey: 'design-section',
    isSection: false,
    daysAgo: 120,
    updatedDaysAgo: 20,
  },
  {
    key: 'design-principles',
    title: 'Design Principles',
    slug: 'design-principles',
    content: '<h2>Our Design Principles</h2><p><strong>1. Show, don\'t tell.</strong> Use progressive disclosure to reveal complexity gradually. Start with the simplest view and let users drill down. Every screen should be useful within 3 seconds of loading.</p><p><strong>2. Data is the hero.</strong> UI chrome should fade into the background. Charts, tables, and numbers should dominate the visual hierarchy. Minimize decorative elements that don\'t serve the data.</p><p><strong>3. Familiar patterns, fresh execution.</strong> Use interaction patterns that users already know (drag-and-drop, context menus, keyboard shortcuts) but execute them with polish and attention to detail. Don\'t reinvent the wheel for basic interactions.</p><p><strong>4. Design for the 80%.</strong> Optimize the default experience for the most common use cases. Power-user features should be accessible but not cluttering the primary interface. Settings and customization live in dedicated panels, not in the main workflow.</p><p><strong>5. Accessible by default.</strong> Accessibility is not a feature — it\'s a quality bar. Every component should work with keyboard navigation, screen readers, and high contrast mode out of the box.</p>',
    category: 'design',
    tags: ['principles', 'design', 'philosophy'],
    type: 'TEAM_DOC',
    createdByKey: 'daniel-nakamura',
    parentKey: 'design-section',
    isSection: false,
    daysAgo: 138,
    updatedDaysAgo: 50,
  },

  // ═══════════════════════════════════════════════════════════
  // GTM DOCS (5 pages)
  // ═══════════════════════════════════════════════════════════
  {
    key: 'gtm-section',
    title: 'Go-to-Market',
    slug: 'go-to-market',
    content: '<h1>Go-to-Market Documentation</h1><p>Sales playbooks, marketing materials, pricing information, and competitive intelligence for the GTM team. Keep these docs current — outdated competitive intel is worse than no competitive intel.</p>',
    category: 'gtm',
    tags: ['gtm', 'sales', 'marketing'],
    type: 'TEAM_DOC',
    createdByKey: 'david-wilson',
    parentKey: null,
    isSection: true,
    daysAgo: 130,
    updatedDaysAgo: 5,
  },
  {
    key: 'sales-playbook',
    title: 'Sales Playbook',
    slug: 'sales-playbook',
    content: '<h2>Ideal Customer Profile</h2><p>Mid-market B2B companies (50-500 employees) with a data team of 2-10 people. Industries: SaaS, fintech, e-commerce, and healthcare. They\'ve outgrown spreadsheet-based reporting but aren\'t ready for a full BI team. Key buyer personas: VP of Data/Analytics, Head of Engineering, or COO.</p><h2>Sales Process</h2><p><strong>Discovery (Week 1):</strong> 30-minute call to understand their current analytics stack, pain points, and timeline. Qualify on BANT (Budget, Authority, Need, Timeline). <strong>Demo (Week 2):</strong> 45-minute personalized demo using their industry\'s data patterns. Show chart creation, data connection, and sharing in under 10 minutes. <strong>Evaluation (Weeks 3-4):</strong> Free trial with white-glove setup. Weekly check-in calls. Success = they create and share 3+ dashboards. <strong>Close (Week 5-6):</strong> Proposal, negotiation, and contract signing.</p><h2>Objection Handling</h2><p><strong>"We already use Tableau":</strong> Acknowledge Tableau\'s power, position Acme as complementary — Acme for business users who don\'t have Tableau licenses. <strong>"Why not just use Metabase?":</strong> Metabase is great for engineering teams but lacks the polish and enterprise features that business users and IT admins need. <strong>"Your pricing is higher than X":</strong> Compare total cost of ownership including training, implementation, and ongoing maintenance. Acme\'s self-serve model eliminates the need for BI consultants.</p>',
    category: 'gtm',
    tags: ['sales', 'playbook', 'process'],
    type: 'TEAM_DOC',
    createdByKey: 'david-wilson',
    parentKey: 'gtm-section',
    isSection: false,
    daysAgo: 110,
    updatedDaysAgo: 12,
  },
  {
    key: 'pricing-guide',
    title: 'Pricing Guide',
    slug: 'pricing-guide',
    content: '<h2>Pricing Tiers</h2><p><strong>Starter ($29/user/month):</strong> Up to 10 users. 5 data source connections. 50 dashboards. Community support. Basic charts (line, bar, pie, table).</p><p><strong>Professional ($59/user/month):</strong> Up to 50 users. Unlimited data sources and dashboards. Email support with 24h SLA. Advanced charts (pivot tables, heatmaps, funnels). API access. Custom branding.</p><p><strong>Enterprise ($99/user/month):</strong> Unlimited users. SSO/SAML. RBAC with custom roles. Audit logging. Dedicated CSM. 4h SLA. SOC 2 compliance. Custom data retention. Priority feature requests.</p><h2>Discounting Guidelines</h2><p>Annual contracts get 20% discount (standard, no approval needed). Multi-year deals: up to 30% with VP approval. Startups (<50 employees, <$5M funding): 50% discount for first year through our startup program. Never discount below $20/user/month — it signals low value.</p><h2>Competitive Pricing</h2><p>Tableau: $70/user/month (Creator), $35/user (Explorer). Looker: custom pricing, typically $50-100/user. Mode: $35/user/month. Metabase: free (open source) or $85/user/month (cloud). We\'re positioned in the middle: more affordable than Tableau/Looker, more capable than Metabase.</p>',
    category: 'gtm',
    tags: ['pricing', 'sales', 'competitive'],
    type: 'TEAM_DOC',
    createdByKey: 'david-wilson',
    parentKey: 'gtm-section',
    isSection: false,
    daysAgo: 95,
    updatedDaysAgo: 18,
  },
  {
    key: 'case-study-dataflow',
    title: 'Case Study: DataFlow Corp',
    slug: 'case-study-dataflow-corp',
    content: '<h2>Customer Overview</h2><p>DataFlow Corp is a 200-person data infrastructure company. Their analytics team of 6 was spending 40% of their time building and maintaining custom dashboards in a homegrown tool. They evaluated Tableau, Looker, and Acme.</p><h2>Challenge</h2><p>The homegrown dashboard tool was slow (30-second load times), difficult to maintain (required engineer time for every new dashboard), and couldn\'t handle their growing data volume (500M rows). Business stakeholders were frustrated with the 2-week turnaround for new reports.</p><h2>Solution</h2><p>DataFlow deployed Acme Analytics to their entire 200-person organization. The analytics team set up data connections and created template dashboards in the first week. Business users were creating their own dashboards by day 3. The drag-and-drop interface eliminated the need for SQL knowledge for basic reports.</p><h2>Results</h2><p>3x faster reporting (from 2 weeks to 2 days for new dashboards). 80% reduction in engineering time spent on dashboards. Dashboard load times under 2 seconds (down from 30 seconds). 90% of business users creating their own reports within the first month. NPS score: 72.</p>',
    category: 'gtm',
    tags: ['case-study', 'customer', 'dataflow'],
    type: 'COMPANY_WIKI',
    createdByKey: 'yuki-tanaka',
    parentKey: 'gtm-section',
    isSection: false,
    daysAgo: 40,
    updatedDaysAgo: 40,
  },
  {
    key: 'marketing-calendar',
    title: 'Marketing Calendar — Q1 2026',
    slug: 'marketing-calendar-q1-2026',
    content: '<h2>January</h2><p>Blog: "5 Signs You\'ve Outgrown Spreadsheet Analytics" (Yuki, published Jan 8). Webinar: "From Spreadsheets to Dashboards in 30 Minutes" (Megan, Jan 22, 150 registrants, 45% show rate). Product Hunt launch follow-up email campaign (3-email sequence, 22% open rate).</p><h2>February</h2><p>Blog: "The True Cost of Building vs. Buying Analytics Tools" (Yuki, published Feb 5). Blog: "How DataFlow Corp Cut Reporting Time by 3x" (Yuki, published Feb 19). Google Ads campaign for "data visualization tools" keywords ($5K budget, targeting 200 demo requests). Conference sponsorship: Data Council (Megan attending, booth + 15-minute lightning talk).</p><h2>March</h2><p>Blog: "Enterprise Analytics Buying Guide 2026" (Yuki, target Mar 5). Webinar: "Building a Data Culture Without a Data Team" (Megan + Sarah, target Mar 19). Case study: TechStart Inc (Yuki, target Mar 15). Website redesign design approval (target Mar 31). LinkedIn campaign targeting VP Analytics titles ($3K budget).</p><h2>Metrics</h2><p>January: 1,200 website visitors → 24 demo requests (2% CVR). Target by March: 2,000 visitors → 60 demo requests (3% CVR). Blog driving 40% of inbound leads. Webinars converting at 15% to demo request.</p>',
    category: 'gtm',
    tags: ['marketing', 'calendar', 'content', 'quarterly'],
    type: 'TEAM_DOC',
    createdByKey: 'megan-obrien',
    parentKey: 'gtm-section',
    isSection: false,
    daysAgo: 60,
    updatedDaysAgo: 5,
  },
  {
    key: 'brand-guidelines',
    title: 'Brand Guidelines',
    slug: 'brand-guidelines',
    content: '<h2>Brand Voice</h2><p><strong>Tone:</strong> Professional but approachable. We\'re experts who explain things simply. Think "helpful colleague" not "corporate vendor." Avoid jargon when a simpler word works. Use "you" and "we" instead of passive voice.</p><p><strong>Writing style:</strong> Short sentences. Active voice. Concrete examples over abstract claims. "Our dashboard loads in under 2 seconds" is better than "We deliver industry-leading performance." Use data to back up claims whenever possible.</p><h2>Logo Usage</h2><p>The Acme Analytics logo uses the wordmark "acme" in lowercase with a stylized bar chart icon. Minimum clear space is 1x the height of the "a" character. The logo should always appear on a solid background — never over busy images or patterns. Available in: full color (blue on white), reversed (white on dark), and monochrome (black on white).</p><h2>Brand Colors</h2><p>Primary brand color: Acme Blue (#2563EB). Use for CTAs, links, and brand accents. Secondary: Slate (#475569) for body text. Accent: Violet (#7C3AED) for highlights and premium features. Never use brand colors at less than 4.5:1 contrast ratio against backgrounds.</p>',
    category: 'gtm',
    tags: ['brand', 'guidelines', 'marketing', 'design'],
    type: 'COMPANY_WIKI',
    createdByKey: 'sophie-dubois',
    parentKey: 'gtm-section',
    isSection: false,
    daysAgo: 85,
    updatedDaysAgo: 30,
  },
]
